/**
 * Exact pre-batch memberships from main 5916b99 (2026-09-15).
 * Recovery only: new attempts must use getChapterTest's current deck.
 * Keep until these snapshot versions can no longer need recovery.
 */
export const PREVIOUS_PRACTICE_TEST_IDS: Readonly<Record<string, readonly string[]>> = {
  "ch-data-sufficiency-t2": ["algebra-q117","arithmetic-q99","data-sufficiency-q46","arithmetic-q86","ratios-percents-q70","number-properties-q46","data-sufficiency-q86","data-sufficiency-q54","data-sufficiency-q68","data-sufficiency-q79"],
  "ch-data-sufficiency-t3": ["data-sufficiency-q80","data-sufficiency-q91","data-sufficiency-q56","data-sufficiency-q96","exponents-roots-q68","data-sufficiency-q84","algebra-q120","data-sufficiency-q66","data-sufficiency-q98","exponents-roots-q80"],
  "ch-verbal-08-cr-flaw-t1": ["critical-reasoning-q74","critical-reasoning-q29","critical-reasoning-q92","critical-reasoning-q216","critical-reasoning-q232","critical-reasoning-q245"],
  "ch-verbal-08-cr-flaw-t2": ["critical-reasoning-q104","critical-reasoning-q47","critical-reasoning-q121","critical-reasoning-q224","critical-reasoning-q239"],
  "ch-table-analysis-t1": ["table-analysis-q48","table-analysis-q58","table-analysis-q36","table-analysis-q38","table-analysis-q39","table-analysis-q44","table-analysis-q47","table-analysis-q51","table-analysis-q52","table-analysis-q55","table-analysis-q59","table-analysis-q60","table-analysis-q63","table-analysis-q64"],
  "ch-table-analysis-t2": ["table-analysis-q67","table-analysis-q72","table-analysis-q79","table-analysis-q80","table-analysis-q81","table-analysis-q82","table-analysis-q84","table-analysis-q86","table-analysis-q88","table-analysis-q90","table-analysis-q91","table-analysis-q93","table-analysis-q40","table-analysis-q42"],
  "ch-table-analysis-t3": ["table-analysis-q57","table-analysis-q61","table-analysis-q65","table-analysis-q69","table-analysis-q73","table-analysis-q76","table-analysis-q77","table-analysis-q78","table-analysis-q83","table-analysis-q85","table-analysis-q87","table-analysis-q89","table-analysis-q92"],
  "ch-graphics-interpretation-t2": ["graphics-interpretation-q50","graphics-interpretation-q53","graphics-interpretation-q56","graphics-interpretation-q57","graphics-interpretation-q60","graphics-interpretation-q61","graphics-interpretation-q64","graphics-interpretation-q65","graphics-interpretation-q69","graphics-interpretation-q72","graphics-interpretation-q73","graphics-interpretation-q77"],
  "ch-graphics-interpretation-t3": ["graphics-interpretation-q79","graphics-interpretation-q85","graphics-interpretation-q90","graphics-interpretation-q91","graphics-interpretation-q92","graphics-interpretation-q34","graphics-interpretation-q38","graphics-interpretation-q44","graphics-interpretation-q49","graphics-interpretation-q54","graphics-interpretation-q58","graphics-interpretation-q62"],
  "ch-quant-21-rate-time-distance-t1": ["rates-work-q27","rates-work-q29","rates-work-q32","rates-work-q57","word-problems-q48","word-problems-q70","word-problems-q82","arithmetic-q85","arithmetic-q97","rates-work-q21","rates-work-q22","rates-work-q35"],
  "ch-quant-21-rate-time-distance-t2": ["rates-work-q37","rates-work-q50","rates-work-q64","rates-work-q67","rates-work-q69","rates-work-q75","ratios-percents-q40","word-problems-q55","word-problems-q79","word-problems-q92","arithmetic-q26"],
  "ch-quant-21-rate-time-distance-t3": ["rates-work-q15","rates-work-q26","rates-work-q43","rates-work-q55","rates-work-q71","rates-work-q73","rates-work-q76","rates-work-q77","rates-work-q80","rates-work-q83","word-problems-q25"],
  "ch-quant-23-statistics-t1": ["statistics-probability-q31","arithmetic-q27","arithmetic-q43","arithmetic-q98","statistics-probability-q26","statistics-probability-q38","statistics-probability-q39","statistics-probability-q40","statistics-probability-q50","statistics-probability-q62"],
  "ch-quant-23-statistics-t2": ["statistics-probability-q64","statistics-probability-q70","statistics-probability-q73","statistics-probability-q78","statistics-probability-q80","statistics-probability-q84","arithmetic-q22","statistics-probability-q22","statistics-probability-q44"],
  "ch-quant-25-permutations-combinations-t1": ["combinatorics-q86","combinatorics-q109","combinatorics-q121","combinatorics-q77","combinatorics-q90","combinatorics-q110","combinatorics-q111","combinatorics-q122","combinatorics-q66","combinatorics-q67","combinatorics-q98","combinatorics-q112","statistics-probability-q20","statistics-probability-q76","statistics-probability-q85"],
  "ch-multi-source-reasoning-t1": ["multi-source-reasoning-q58","multi-source-reasoning-q66","multi-source-reasoning-q16","multi-source-reasoning-q17","multi-source-reasoning-q19","multi-source-reasoning-q20","multi-source-reasoning-q25","multi-source-reasoning-q26","multi-source-reasoning-q28","multi-source-reasoning-q30","multi-source-reasoning-q32","multi-source-reasoning-q34","multi-source-reasoning-q35","multi-source-reasoning-q59"],
  "ch-multi-source-reasoning-t2": ["multi-source-reasoning-q60","multi-source-reasoning-q64","multi-source-reasoning-q67","multi-source-reasoning-q70","multi-source-reasoning-q71","multi-source-reasoning-q73","multi-source-reasoning-q74","multi-source-reasoning-q76","multi-source-reasoning-q78","multi-source-reasoning-q83","multi-source-reasoning-q84","multi-source-reasoning-q87","multi-source-reasoning-q18"],
  "ch-multi-source-reasoning-t3": ["multi-source-reasoning-q21","multi-source-reasoning-q24","multi-source-reasoning-q27","multi-source-reasoning-q29","multi-source-reasoning-q33","multi-source-reasoning-q36","multi-source-reasoning-q61","multi-source-reasoning-q72","multi-source-reasoning-q75","multi-source-reasoning-q77","multi-source-reasoning-q79","multi-source-reasoning-q82","multi-source-reasoning-q86"],
  "ch-quant-27-probability-t1": ["combinatorics-q33","combinatorics-q76","combinatorics-q88","statistics-probability-q2","statistics-probability-q30","statistics-probability-q32","statistics-probability-q33","statistics-probability-q49","statistics-probability-q59","statistics-probability-q61","combinatorics-q36","combinatorics-q37"],
  "ch-quant-27-probability-t2": ["combinatorics-q39","combinatorics-q41","combinatorics-q79","statistics-probability-q18","statistics-probability-q23","statistics-probability-q29","statistics-probability-q34","statistics-probability-q35","statistics-probability-q36","statistics-probability-q63","statistics-probability-q65","statistics-probability-q74"],
  "ch-quant-27-probability-t3": ["statistics-probability-q83","combinatorics-q42","combinatorics-q44","combinatorics-q95","statistics-probability-q25","statistics-probability-q41","statistics-probability-q42","statistics-probability-q45","statistics-probability-q55","statistics-probability-q56","statistics-probability-q77","statistics-probability-q79"],
}
