import { describe, expect, it } from "vitest"
import { getQuestionsByIds } from "@/lib/content"

const COMBINED_DI_BATCH_IDS = [
  "two-part-analysis-q49",
  "two-part-analysis-q14",
  "two-part-analysis-q35",
  "two-part-analysis-q8",
  "two-part-analysis-q33",
  "two-part-analysis-q6",
  "two-part-analysis-q45",
  "two-part-analysis-q84",
  "two-part-analysis-q94",
  "two-part-analysis-q95",
  "two-part-analysis-q13",
  "multi-source-reasoning-q8",
  "multi-source-reasoning-q12",
  "two-part-analysis-q81",
  "two-part-analysis-q39",
  "multi-source-reasoning-q80",
  "multi-source-reasoning-q15",
  "multi-source-reasoning-q16",
  "multi-source-reasoning-q22",
  "multi-source-reasoning-q82",
  "graphics-interpretation-q46",
  "graphics-interpretation-q19",
  "table-analysis-q5",
  "graphics-interpretation-q28",
  "two-part-analysis-q4",
  "two-part-analysis-q91",
  "data-sufficiency-q13",
  "two-part-analysis-q64",
  "multi-source-reasoning-q19",
  "two-part-analysis-q60",
  "ratios-percents-q45",
  "multi-source-reasoning-q9",
  "multi-source-reasoning-q21",
  "two-part-analysis-q73",
  "two-part-analysis-q12",
  "graphics-interpretation-q82",
  "two-part-analysis-q15",
  "two-part-analysis-q59",
  "graphics-interpretation-q44",
  "two-part-analysis-q72",
  "graphics-interpretation-q6",
  "graphics-interpretation-q38",
  "multi-source-reasoning-q25",
  "multi-source-reasoning-q5",
  "two-part-analysis-q20",
  "two-part-analysis-q34",
  "table-analysis-q29",
  "two-part-analysis-q46",
  "table-analysis-q36",
  "two-part-analysis-q18",
  "data-sufficiency-q44",
  "multi-source-reasoning-q86",
  "graphics-interpretation-q35",
  "two-part-analysis-q51",
  "graphics-interpretation-q88",
  "two-part-analysis-q25",
  "two-part-analysis-q61",
  "table-analysis-q37",
  "word-problems-q20",
  "graphics-interpretation-q5",
] as const

const EXTREME_CLARITY_BATCH_IDS = [
  "reading-comprehension-q39",
  "reading-comprehension-q50",
  "reading-comprehension-q24",
  "reading-comprehension-q29",
  "reading-comprehension-q19",
  "reading-comprehension-q52",
  "reading-comprehension-q4",
  "reading-comprehension-q41",
  "reading-comprehension-q3",
  "reading-comprehension-q32",
  "reading-comprehension-q63",
  "reading-comprehension-q25",
  "reading-comprehension-q51",
  "reading-comprehension-q73",
  "reading-comprehension-q33",
  "reading-comprehension-q49",
  "reading-comprehension-q17",
  "reading-comprehension-q37",
  "reading-comprehension-q57",
  "reading-comprehension-q34",
  "reading-comprehension-q71",
  "reading-comprehension-q47",
  "reading-comprehension-q31",
  "reading-comprehension-q64",
  "reading-comprehension-q11",
  "reading-comprehension-q45",
  "reading-comprehension-q61",
  "reading-comprehension-q53",
  "reading-comprehension-q55",
  "reading-comprehension-q9",
  "ratios-percents-q50",
  "reading-comprehension-q58",
  "reading-comprehension-q35",
  "reading-comprehension-q43",
  "algebra-q28",
  "multi-source-reasoning-q30",
  "multi-source-reasoning-q79",
  "reading-comprehension-q56",
] as const

const PASS_10_IDS = [
  "two-part-analysis-q52",
  "two-part-analysis-q78",
  "multi-source-reasoning-q34",
  "reading-comprehension-q40",
  "reading-comprehension-q21",
  "graphics-interpretation-q41",
  "multi-source-reasoning-q4",
  "combinatorics-q45",
  "data-sufficiency-q43",
  "reading-comprehension-q36",
  "reading-comprehension-q2",
  "reading-comprehension-q54",
  "multi-source-reasoning-q36",
  "ratios-percents-q18",
  "reading-comprehension-q27",
  "reading-comprehension-q70",
  "graphics-interpretation-q27",
  "reading-comprehension-q44",
  "reading-comprehension-q13",
  "reading-comprehension-q20",
  "multi-source-reasoning-q78",
  "multi-source-reasoning-q14",
  "reading-comprehension-q15",
  "multi-source-reasoning-q63",
  "reading-comprehension-q28",
  "rates-work-q26",
  "multi-source-reasoning-q87",
  "reading-comprehension-q59",
  "multi-source-reasoning-q2",
  "two-part-analysis-q48",
  "q-quant-01-mindset-q8",
  "graphics-interpretation-q37",
  "reading-comprehension-q5",
  "reading-comprehension-q48",
  "reading-comprehension-q38",
  "multi-source-reasoning-q85",
  "reading-comprehension-q23",
  "q-quant-01-mindset-q6",
  "two-part-analysis-q1",
  "reading-comprehension-q7",
  "critical-reasoning-q5",
  "multi-source-reasoning-q29",
  "reading-comprehension-q46",
  "multi-source-reasoning-q72",
  "two-part-analysis-q93",
  "combinatorics-q42",
  "reading-comprehension-q62",
  "graphics-interpretation-q36",
  "multi-source-reasoning-q3",
  "multi-source-reasoning-q20",
  "multi-source-reasoning-q7",
  "reading-comprehension-q30",
  "reading-comprehension-q16",
  "multi-source-reasoning-q67",
  "two-part-analysis-q5",
  "data-sufficiency-q25",
  "data-sufficiency-q48",
  "two-part-analysis-q7",
  "table-analysis-q40",
  "two-part-analysis-q28",
] as const

const CLARITY_BATCH_IDS = [
  ...Array.from({ length: 51 }, (_, index) => `number-properties-q${index + 1}`),
  ...Array.from({ length: 65 }, (_, index) => `statistics-probability-q${index + 21}`),
  "graphics-interpretation-q1",
  "graphics-interpretation-q11",
  "graphics-interpretation-q16",
  "graphics-interpretation-q30",
  "table-analysis-q62",
  ...COMBINED_DI_BATCH_IDS,
  ...EXTREME_CLARITY_BATCH_IDS,
  ...PASS_10_IDS,
] as const

describe("explanation clarity batch", () => {
  const questions = getQuestionsByIds(CLARITY_BATCH_IDS)

  it("keeps every reviewed question addressable", () => {
    expect(questions).toHaveLength(CLARITY_BATCH_IDS.length)
  })

  it("leads with a concise test-day method and ends with a transferable lesson", () => {
    for (const question of questions) {
      expect(question.fastestPath, question.id).toBeTruthy()
      expect(question.takeaway, question.id).toBeTruthy()
      expect(question.fastestPath!.length, question.id).toBeLessThanOrEqual(220)
      expect(question.takeaway!.length, question.id).toBeLessThanOrEqual(160)
    }
  })

  it("keeps the supporting explanation substantive and free of abstract boilerplate", () => {
    const abstractOpening = /^(?:the governing principle|this problem is governed)/i

    for (const question of questions) {
      expect(question.explanation.trim().length, question.id).toBeGreaterThanOrEqual(120)
      expect(question.explanation.trim(), question.id).not.toMatch(abstractOpening)
    }
  })

  it("preserves the reviewed answer keys", () => {
    const expectedAnswers: Record<string, string> = {
      "number-properties-q1": "B",
      "number-properties-q2": "C",
      "number-properties-q3": "D",
      "number-properties-q4": "C",
      "number-properties-q5": "D",
      "number-properties-q6": "E",
      "number-properties-q7": "D",
      "number-properties-q8": "B",
      "number-properties-q9": "A",
      "number-properties-q10": "C",
      "number-properties-q11": "B",
      "number-properties-q12": "E",
      "number-properties-q13": "C",
      "number-properties-q14": "C",
      "number-properties-q15": "C",
      "number-properties-q16": "C",
      "number-properties-q17": "B",
      "number-properties-q18": "A",
      "number-properties-q19": "C",
      "number-properties-q20": "D",
      "number-properties-q21": "D",
      "number-properties-q22": "C",
      "number-properties-q23": "C",
      "number-properties-q24": "C",
      "number-properties-q25": "C",
      "number-properties-q26": "B",
      "number-properties-q27": "B",
      "number-properties-q28": "D",
      "number-properties-q29": "B",
      "number-properties-q30": "B",
      "number-properties-q31": "B",
      "number-properties-q32": "D",
      "number-properties-q33": "C",
      "number-properties-q34": "D",
      "number-properties-q35": "D",
      "number-properties-q36": "E",
      "number-properties-q37": "C",
      "number-properties-q38": "C",
      "number-properties-q39": "C",
      "number-properties-q40": "B",
      "number-properties-q41": "D",
      "number-properties-q42": "C",
      "number-properties-q43": "C",
      "number-properties-q44": "C",
      "number-properties-q45": "C",
      "number-properties-q46": "A",
      "number-properties-q47": "C",
      "number-properties-q48": "B",
      "number-properties-q49": "D",
      "number-properties-q50": "B",
      "number-properties-q51": "C",
      "statistics-probability-q21": "B",
      "statistics-probability-q22": "C",
      "statistics-probability-q23": "C",
      "statistics-probability-q24": "B",
      "statistics-probability-q25": "C",
      "statistics-probability-q26": "B",
      "statistics-probability-q27": "E",
      "statistics-probability-q28": "C",
      "statistics-probability-q29": "B",
      "statistics-probability-q30": "B",
      "statistics-probability-q31": "C",
      "statistics-probability-q32": "D",
      "statistics-probability-q33": "A",
      "statistics-probability-q34": "D",
      "statistics-probability-q35": "C",
      "statistics-probability-q36": "D",
      "statistics-probability-q37": "D",
      "statistics-probability-q38": "D",
      "statistics-probability-q39": "D",
      "statistics-probability-q40": "C",
      "statistics-probability-q41": "B",
      "statistics-probability-q42": "E",
      "statistics-probability-q43": "B",
      "statistics-probability-q44": "C",
      "statistics-probability-q45": "D",
      "statistics-probability-q46": "C",
      "statistics-probability-q47": "D",
      "statistics-probability-q48": "A",
      "statistics-probability-q49": "B",
      "statistics-probability-q50": "E",
      "statistics-probability-q51": "B",
      "statistics-probability-q52": "C",
      "statistics-probability-q53": "C",
      "statistics-probability-q54": "B",
      "statistics-probability-q55": "A",
      "statistics-probability-q56": "E",
      "statistics-probability-q57": "D",
      "statistics-probability-q58": "B",
      "statistics-probability-q59": "E",
      "statistics-probability-q60": "A",
      "statistics-probability-q61": "D",
      "statistics-probability-q62": "C",
      "statistics-probability-q63": "B",
      "statistics-probability-q64": "A",
      "statistics-probability-q65": "C",
      "statistics-probability-q66": "C",
      "statistics-probability-q67": "A",
      "statistics-probability-q68": "D",
      "statistics-probability-q69": "E",
      "statistics-probability-q70": "D",
      "statistics-probability-q71": "E",
      "statistics-probability-q72": "C",
      "statistics-probability-q73": "D",
      "statistics-probability-q74": "D",
      "statistics-probability-q75": "B",
      "statistics-probability-q76": "B",
      "statistics-probability-q77": "C",
      "statistics-probability-q78": "D",
      "statistics-probability-q79": "B",
      "statistics-probability-q80": "D",
      "statistics-probability-q81": "C",
      "statistics-probability-q82": "B",
      "statistics-probability-q83": "D",
      "statistics-probability-q84": "C",
      "statistics-probability-q85": "D",
      "graphics-interpretation-q1": "C",
      "graphics-interpretation-q11": "C",
      "graphics-interpretation-q16": "E",
      "graphics-interpretation-q30": "B",
      "table-analysis-q62": "C",
      "multi-source-reasoning-q8": "A",
      "multi-source-reasoning-q12": "B",
      "multi-source-reasoning-q80": "B",
      "multi-source-reasoning-q15": "C",
      "multi-source-reasoning-q16": "A",
      "multi-source-reasoning-q22": "E",
      "multi-source-reasoning-q82": "E",
      "graphics-interpretation-q46": "D",
      "graphics-interpretation-q19": "C",
      "table-analysis-q5": "A",
      "graphics-interpretation-q28": "B",
      "data-sufficiency-q13": "C",
      "multi-source-reasoning-q19": "D",
      "ratios-percents-q45": "C",
      "multi-source-reasoning-q9": "A",
      "multi-source-reasoning-q21": "E",
      "graphics-interpretation-q82": "C",
      "graphics-interpretation-q44": "C",
      "graphics-interpretation-q6": "A",
      "graphics-interpretation-q38": "C",
      "multi-source-reasoning-q25": "D",
      "multi-source-reasoning-q5": "B",
      "table-analysis-q29": "B",
      "table-analysis-q36": "B",
      "data-sufficiency-q44": "C",
      "multi-source-reasoning-q86": "B",
      "graphics-interpretation-q35": "C",
      "graphics-interpretation-q88": "B",
      "table-analysis-q37": "B",
      "word-problems-q20": "C",
      "graphics-interpretation-q5": "A",
      "reading-comprehension-q39": "E",
      "reading-comprehension-q50": "D",
      "reading-comprehension-q24": "C",
      "reading-comprehension-q29": "D",
      "reading-comprehension-q19": "E",
      "reading-comprehension-q52": "C",
      "reading-comprehension-q4": "E",
      "reading-comprehension-q41": "C",
      "reading-comprehension-q3": "E",
      "reading-comprehension-q32": "D",
      "reading-comprehension-q63": "D",
      "reading-comprehension-q25": "E",
      "reading-comprehension-q51": "A",
      "reading-comprehension-q73": "C",
      "reading-comprehension-q33": "E",
      "reading-comprehension-q49": "D",
      "reading-comprehension-q17": "E",
      "reading-comprehension-q37": "C",
      "reading-comprehension-q57": "D",
      "reading-comprehension-q34": "C",
      "reading-comprehension-q71": "E",
      "reading-comprehension-q47": "C",
      "reading-comprehension-q31": "A",
      "reading-comprehension-q64": "A",
      "reading-comprehension-q11": "E",
      "reading-comprehension-q45": "C",
      "reading-comprehension-q61": "A",
      "reading-comprehension-q53": "E",
      "reading-comprehension-q55": "A",
      "reading-comprehension-q9": "E",
      "ratios-percents-q50": "B",
      "reading-comprehension-q58": "A",
      "reading-comprehension-q35": "A",
      "reading-comprehension-q43": "D",
      "algebra-q28": "C",
      "multi-source-reasoning-q30": "D",
      "multi-source-reasoning-q79": "B",
      "reading-comprehension-q56": "D",
      "multi-source-reasoning-q34": "D",
      "reading-comprehension-q40": "C",
      "reading-comprehension-q21": "E",
      "graphics-interpretation-q41": "A",
      "multi-source-reasoning-q4": "B",
      "combinatorics-q45": "B",
      "data-sufficiency-q43": "C",
      "reading-comprehension-q36": "C",
      "reading-comprehension-q2": "E",
      "reading-comprehension-q54": "C",
      "multi-source-reasoning-q36": "C",
      "ratios-percents-q18": "C",
      "reading-comprehension-q27": "C",
      "reading-comprehension-q70": "A",
      "graphics-interpretation-q27": "E",
      "reading-comprehension-q44": "E",
      "reading-comprehension-q13": "E",
      "reading-comprehension-q20": "D",
      "multi-source-reasoning-q78": "B",
      "multi-source-reasoning-q14": "A",
      "reading-comprehension-q15": "E",
      "multi-source-reasoning-q63": "B",
      "reading-comprehension-q28": "C",
      "rates-work-q26": "D",
      "multi-source-reasoning-q87": "C",
      "reading-comprehension-q59": "E",
      "multi-source-reasoning-q2": "A",
      "q-quant-01-mindset-q8": "C",
      "graphics-interpretation-q37": "B",
      "reading-comprehension-q5": "D",
      "reading-comprehension-q48": "C",
      "reading-comprehension-q38": "D",
      "multi-source-reasoning-q85": "D",
      "reading-comprehension-q23": "D",
      "q-quant-01-mindset-q6": "D",
      "reading-comprehension-q7": "D",
      "critical-reasoning-q5": "E",
      "multi-source-reasoning-q29": "E",
      "reading-comprehension-q46": "A",
      "multi-source-reasoning-q72": "C",
      "combinatorics-q42": "C",
      "reading-comprehension-q62": "A",
      "graphics-interpretation-q36": "B",
      "multi-source-reasoning-q3": "A",
      "multi-source-reasoning-q20": "E",
      "multi-source-reasoning-q7": "B",
      "reading-comprehension-q30": "E",
      "reading-comprehension-q16": "D",
      "multi-source-reasoning-q67": "A",
      "data-sufficiency-q25": "E",
      "data-sufficiency-q48": "C",
      "table-analysis-q40": "C",
    }

    const expectedTwoPartAnswers: Record<string, readonly [number, number]> = {
      "two-part-analysis-q49": [0, 2],
      "two-part-analysis-q14": [0, 1],
      "two-part-analysis-q35": [0, 1],
      "two-part-analysis-q8": [0, 1],
      "two-part-analysis-q33": [0, 2],
      "two-part-analysis-q6": [0, 1],
      "two-part-analysis-q45": [0, 1],
      "two-part-analysis-q84": [0, 1],
      "two-part-analysis-q94": [0, 1],
      "two-part-analysis-q95": [0, 1],
      "two-part-analysis-q13": [0, 1],
      "two-part-analysis-q81": [1, 3],
      "two-part-analysis-q39": [1, 3],
      "two-part-analysis-q4": [2, 0],
      "two-part-analysis-q91": [0, 1],
      "two-part-analysis-q64": [0, 1],
      "two-part-analysis-q60": [0, 1],
      "two-part-analysis-q73": [0, 1],
      "two-part-analysis-q12": [4, 1],
      "two-part-analysis-q15": [2, 4],
      "two-part-analysis-q59": [0, 1],
      "two-part-analysis-q72": [0, 1],
      "two-part-analysis-q20": [2, 3],
      "two-part-analysis-q34": [1, 4],
      "two-part-analysis-q46": [4, 1],
      "two-part-analysis-q18": [0, 2],
      "two-part-analysis-q51": [2, 2],
      "two-part-analysis-q25": [2, 4],
      "two-part-analysis-q61": [1, 4],
      "two-part-analysis-q52": [1, 5],
      "two-part-analysis-q78": [1, 5],
      "two-part-analysis-q48": [3, 3],
      "two-part-analysis-q1": [1, 4],
      "two-part-analysis-q93": [4, 1],
      "two-part-analysis-q5": [1, 3],
      "two-part-analysis-q7": [3, 1],
      "two-part-analysis-q28": [3, 2],
    }

    for (const question of questions) {
      const expectedAnswer = expectedAnswers[question.id]
      const expectedTwoPart = expectedTwoPartAnswers[question.id]

      expect(Boolean(expectedAnswer || expectedTwoPart), question.id).toBe(true)
      if (expectedTwoPart) {
        expect(question.twoPartCorrectAnswers, question.id).toEqual(expectedTwoPart)
      } else {
        expect(question.correctAnswerLetter, question.id).toBe(expectedAnswer)
      }
    }
  })
})
